/*
 * Copyright (C) 2025 Davide Fuscà
 *
 * This file is part of BumbleBee.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */
#pragma once
#include "PhysicalRule.hpp"

namespace bumblebee{

// Executor of a Physical Rule.
// Each execution runs in its own thread.
// Manages the local state of the physical atom (patom).
//
// Execution flow:
// - Initialize patom states
// - Retrieve data from the source patom
// - Process data through the chain
// - Send output to the sink
//
// The `finalize` method of the patom is called by the scheduler
// once all threads have completed execution.
class PhysicalRuleExecutor {
public:
    explicit PhysicalRuleExecutor(prule_ptr_t prule, ThreadContext *context);
    PhysicalRuleExecutor(PhysicalRuleExecutor&& other) = default;

    // Execute the Physical rule
    void execute();
    // Execute the intermediate patom pushing the chunks
    void executePush();
    // Execute the combine (sink)
    void executeCombine();
    // Fetch from the source
    void fetchFromSource(DataChunk& input);
    // Call the finalize on the sink and source patoms, It is called only once per pipeline
    void finalize();
    // init function to call before the execute
    void initialize();

private:
    void initializeStates();
    void initializeChunks();

    ThreadContext* tcontext_;
    // The physical rule to be executed
    prule_ptr_t prule_;

    pstate_ptr_vector_t states_;
    // chunks, first chunk is the chunk generated by the source, last chunk is the chunk to sink
    data_chunk_vector_t chunks_;
    // local source and sink states
    pstate_ptr_t sourceState_;
    pstate_ptr_t sinkState_;
    // result type for each intermediate physical atom
    vector<AtomResultType> atomResults_;
    AtomResultType sinkResult_;
    AtomResultType sourceResult_;

    bool finished_{false};

    // TODO Execution context with a  profiler
};

using rule_executor_ptr_t = std::shared_ptr<PhysicalRuleExecutor>;

}
