%@sql
SELECT SEARCHENGINEID, CLIENTIP, COUNT(*) AS c, SUM(ISREFRESH) as sum, AVG(RESOLUTIONWIDTH) as avg
FROM "./files/parquet/mini_hits.parquet"
WHERE SEARCHPHRASE <> ""
GROUP BY SEARCHENGINEID, CLIENTIP
ORDER BY c DESC, CLIENTIP LIMIT 10
