%@sql
SELECT WATCHID, CLIENTIP, COUNT(*) AS c, SUM(ISREFRESH) as sum, AVG(RESOLUTIONWIDTH) as avg
FROM "./files/parquet/mini_hits.parquet"
WHERE SEARCHPHRASE <> ""
GROUP BY WATCHID, CLIENTIP
ORDER BY c DESC, CLIENTIP DESC, avg LIMIT 3
