%@sql
SELECT WATCHID, CLIENTIP, COUNT(*) AS c, SUM(ISREFRESH) as sum, AVG(RESOLUTIONWIDTH) as avg
FROM "./files/csv/mini_hits.csv"
WHERE SEARCHPHRASE <> ""
GROUP BY WATCHID, CLIENTIP
ORDER BY c DESC, CLIENTIP DESC, avg LIMIT 3
