%@sql
SELECT WATCHID, CLIENTIP, COUNT(*) AS c, SUM(ISREFRESH) AS sum, AVG(RESOLUTIONWIDTH) AS avg
FROM "./files/parquet/mini_hits.parquet"
GROUP BY WATCHID, CLIENTIP
ORDER BY c DESC, WATCHID DESC
LIMIT 10