%@sql
SELECT TITLE, COUNT(*) AS PageViews
FROM "./files/parquet/mini_hits.parquet"
WHERE COUNTERID = 62 AND EVENTDATE >= "2013-07-01" AND EVENTDATE <= "2013-07-31" AND DONTCOUNTHITS = 0 AND ISREFRESH = 0 AND TITLE <> ""
GROUP BY TITLE
ORDER BY PageViews DESC LIMIT 10